// Generated by wrangler types
// This file is required for wrangler v4+ TypeScript support

interface Env {
	// Add any Cloudflare Workers bindings here if needed
}

declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
