import fs from 'node:fs';
import path from 'node:path';

type PublicFacility = {
	id?: unknown;
	ward_id?: unknown;
	name?: unknown;
	address?: unknown;
	latitude?: unknown;
	longitude?: unknown;
	categories?: unknown;
	geocode_confidence?: unknown;
	geocode_status?: unknown;
};

type PublicData = {
	facilities?: PublicFacility[];
};

type Issue = {
	id: string;
	message: string;
};

const inputPath = process.argv[2];

if (!inputPath) {
	console.error('Usage: npm run validate:d1-seed -- /private/path/public-d1-seed.json');
	console.error('The seed JSON must be generated by the private data pipeline and must not be committed.');
	process.exit(2);
}

const resolvedPath = path.resolve(inputPath);
const data = JSON.parse(fs.readFileSync(resolvedPath, 'utf-8')) as PublicData;
const facilities = Array.isArray(data.facilities) ? data.facilities : [];
const issues: Issue[] = [];
const ids = new Set<string>();

function text(value: unknown): string {
	return typeof value === 'string' ? value.trim() : '';
}

function number(value: unknown): number | null {
	return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

for (const facility of facilities) {
	const id = text(facility.id) || '(missing id)';
	const latitude = number(facility.latitude);
	const longitude = number(facility.longitude);
	const categories = Array.isArray(facility.categories)
		? facility.categories.filter((category): category is string => typeof category === 'string' && category.trim().length > 0)
		: [];

	if (!text(facility.id)) issues.push({ id, message: 'missing id' });
	if (ids.has(id)) issues.push({ id, message: 'duplicate public facility id' });
	ids.add(id);
	if (!text(facility.ward_id)) issues.push({ id, message: 'missing ward_id' });
	if (!text(facility.name)) issues.push({ id, message: 'missing name' });
	if (!text(facility.address)) issues.push({ id, message: 'missing address' });
	if (latitude === null || latitude < 20 || latitude > 46) issues.push({ id, message: 'invalid latitude' });
	if (longitude === null || longitude < 122 || longitude > 154) issues.push({ id, message: 'invalid longitude' });
	if (categories.length === 0) issues.push({ id, message: 'missing categories' });
	if (facility.geocode_status === 'failed') issues.push({ id, message: 'unresolved failed geocoding row' });
	if (facility.geocode_confidence === 'low') issues.push({ id, message: 'unresolved low-confidence geocoding row' });
}

if (facilities.length === 0) {
	issues.push({ id: '(dataset)', message: 'no facilities found' });
}

if (issues.length > 0) {
	console.error(`D1 public data validation failed: ${issues.length} issue(s)`);
	for (const issue of issues.slice(0, 100)) {
		console.error(`- ${issue.id}: ${issue.message}`);
	}
	if (issues.length > 100) {
		console.error(`...and ${issues.length - 100} more`);
	}
	process.exit(1);
}

console.log(`D1 public data validation passed: ${facilities.length} facilities`);
